### ISSUE TITLE
Is animation time wrong in mixin?

### ISSUE THREAD

**Issue by MatejKustec** [eggboxio/waitanimate#2]
Hello I just started using your mixin and I discovered that animation time is different in your mixin output as in "Custom animation" generator on your site. So if I set ` duration: 3,
    waitTime: 5,` in mixin, my output is `3s`. If I set same settings in your "Custom animation" generator, output result is `8s`. So is there maybe missing `#{$duration + $waitTime}s` at animation output?

**Comment by eggboxio** [comment]
Thanks for spotting this. I've updated the mixin details.
